import { useParams, useNavigate } from 'react-router-dom';
import { useGigStore } from '@/stores/gigStore';
import { useSongStore } from '@/stores/songStore';
import { getEffectiveKey } from '@/lib/helpers';

export default function PrintView() {
  const { gigId } = useParams<{ gigId: string }>();
  const navigate = useNavigate();
  const gig = useGigStore((s) => s.gigs.find((g) => g.id === gigId));
  const songs = useSongStore((s) => s.songs);

  if (!gig) return <div className="flex items-center justify-center h-screen"><p>Gig not found</p></div>;

  const dateStr = new Date(gig.date + 'T12:00:00').toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

  return (
    <div className="min-h-screen bg-white text-black">
      <div className="no-print flex items-center gap-3 p-4 bg-background text-foreground border-b border-border">
        <button className="text-sm hover:bg-accent px-3 py-1.5 rounded" onClick={() => navigate(`/gig/${gigId}`)}>← Back</button>
        <div className="flex-1" />
        <button className="text-sm bg-primary text-primary-foreground px-3 py-1.5 rounded font-medium" onClick={() => window.print()}>🖨 Print / Download PDF</button>
      </div>
      <div className="max-w-[7.5in] mx-auto px-[0.5in] py-[0.4in]" style={{ fontFamily: "'Figtree', 'Helvetica Neue', Arial, sans-serif" }}>
        <div className="text-center mb-6">
          <h1 className="text-2xl font-bold uppercase tracking-wider">{gig.name}</h1>
          <p className="text-sm text-gray-500 mt-1">{dateStr} — {gig.venue}</p>
        </div>
        {gig.sets.map((set) => (
          <div key={set.id} className="mb-5">
            <div className="border-b-2 border-black pb-1 mb-3">
              <h2 className="text-sm font-bold uppercase tracking-widest">{set.name}</h2>
            </div>
            <div className="space-y-1.5">
              {set.entries.map((entry, ei) => {
                const song = songs.find((s) => s.id === entry.songId);
                if (!song) return null;
                const key = getEffectiveKey(song, entry.versionId, entry.keyOverride);
                return (
                  <div key={entry.id} className="flex items-baseline gap-2" style={{ fontSize: '14pt', lineHeight: '1.6' }}>
                    <span className="text-gray-400 font-mono text-xs w-5 text-right shrink-0" style={{ fontSize: '10pt' }}>{ei + 1}.</span>
                    <span className="font-semibold flex-1">{song.title}</span>
                    <span className="border-b border-dotted border-gray-300 flex-1 mx-1 min-w-[2rem]" />
                    <span className="font-mono font-bold text-right shrink-0" style={{ minWidth: '2rem' }}>{key}</span>
                  </div>
                );
              })}
              {set.entries.length === 0 && <p className="text-sm text-gray-400 italic text-center py-2">No songs</p>}
            </div>
          </div>
        ))}
        <div className="mt-8 pt-3 border-t border-gray-200 text-center">
          <p className="text-[9pt] text-gray-400">Generated by Setlist Builder</p>
        </div>
      </div>
    </div>
  );
}
